# Your Name or Company
title: Shivangi Dwivedi

# Description of your website. This is used for social sharing.
description: Gender | Capacity Building | Research and Analysis | Shivangi Dwivedi

# A brief blurb about yourself
content: Shivangi Dwivedi currently works as a Manager, Rehabilitation and Advocacy at Vimochana Collective, Bangalore. In the past she has worked as a research fellow at Janvikas, Ahmedabad, where she conceptualized and designed programs to empower women to collectively address community issues by creating a network of women journalists in rural Gujarat among other things. She has also worked as a Reseach associate at IIM Ahmedabad, where she aided in creating an impact measurement framework by conducting research into Social Enterprises, existing frameworks and Impact Investors. She has also worked as a research intern at CLAWS, where she Conducted study on conflict in Manipur and social, economic and international ramifications. Results further published as an article on CLAWS and as a paper in a compendium published by the Assam Rifles.

# Add your social links
social:
  #  - platform: github
  #  url: https://github.com/
  # - platform: facebook
  #  url: https://facebook.com/
  - platform: twitter
    url: https://twitter.com/shivangi931
  - platform: linkedin
    url: shivangi-dwivedi-603333109

# General settings
markdown: kramdown
sharing_image: shivangi_dwivedi_landing_page.jpg

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
